# Generated by Django 2.2 on 2021-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='is_like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topics',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
