# Generated by Django 2.2 on 2021-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='level',
            field=models.CharField(default='', max_length=255, verbose_name='评论层级'),
        ),
    ]
