# Generated by Django 2.2 on 2021-07-13 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210713_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.CharField(max_length=191, verbose_name='请求地址')),
                ('ip', models.CharField(max_length=64)),
                ('params', models.TextField(verbose_name='请求参数')),
                ('create_time', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '日志记录表',
                'verbose_name': '日志记录表',
                'db_table': 'logs',
            },
        ),
    ]
