# Generated by Django 2.2 on 2021-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='异常内容'),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(default='info', max_length=32, verbose_name='异常级别'),
        ),
    ]
