# Generated by Django 2.2 on 2021-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20210713_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sign',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
