# Generated by Django 2.2 on 2021-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_users_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(default='/avatars/avatar.jpg', upload_to='avatars/'),
        ),
    ]
