# Generated by Django 2.2 on 2021-07-17 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20210715_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
