# Generated by Django 2.2 on 2021-07-22 22:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20210717_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
    ]
